# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 221, 311))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.train_seq_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.train_seq_layout.setContentsMargins(0, 0, 0, 0)
        self.train_seq_layout.setObjectName("train_seq_layout")
        self.train_seq_list = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.train_seq_list.setObjectName("train_seq_list")
        self.train_seq_layout.addWidget(self.train_seq_list)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(240, 30, 205, 311))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.hit_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.hit_layout.setContentsMargins(0, 0, 0, 0)
        self.hit_layout.setObjectName("hit_layout")
        self.hit_table = QtWidgets.QTableWidget(self.horizontalLayoutWidget_2)
        self.hit_table.setObjectName("hit_table")
        self.hit_table.setColumnCount(2)
        self.hit_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.hit_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hit_table.setHorizontalHeaderItem(1, item)
        self.hit_layout.addWidget(self.hit_table)
        self.train_seq_list_label = QtWidgets.QLabel(self.centralwidget)
        self.train_seq_list_label.setGeometry(QtCore.QRect(20, 10, 161, 16))
        self.train_seq_list_label.setObjectName("train_seq_list_label")
        self.hit_table_label = QtWidgets.QLabel(self.centralwidget)
        self.hit_table_label.setGeometry(QtCore.QRect(310, 10, 61, 16))
        self.hit_table_label.setObjectName("hit_table_label")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 380, 436, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.info_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.info_layout.setContentsMargins(0, 0, 0, 0)
        self.info_layout.setObjectName("info_layout")
        self.info_list = QtWidgets.QListWidget(self.horizontalLayoutWidget_3)
        self.info_list.setObjectName("info_list")
        item = QtWidgets.QListWidgetItem()
        self.info_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.info_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.info_list.addItem(item)
        self.info_layout.addWidget(self.info_list)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 360, 151, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.hit_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sensor ID"))
        item = self.hit_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tempo"))
        self.train_seq_list_label.setText(_translate("MainWindow", "Treinamentos disponíveis:"))
        self.hit_table_label.setText(_translate("MainWindow", "Resultados"))
        __sortingEnabled = self.info_list.isSortingEnabled()
        self.info_list.setSortingEnabled(False)
        item = self.info_list.item(0)
        item.setText(_translate("MainWindow", "Nome                       : "))
        item = self.info_list.item(1)
        item.setText(_translate("MainWindow", "Número de Golpes : "))
        item = self.info_list.item(2)
        item.setText(_translate("MainWindow", "Sequência                :"))
        self.info_list.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Informação do Treinamento:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))


